language: csharp
mono: none
dotnet: 2.0.0
branches:
 only:
  - master
script:
  - dotnet build ./ContactList.WebApi/ContactList.sln -c Release
deploy:
  provider: pages
  skip-cleanup: true
  github-token: contactlistToken
  keep-history: true
  on:
    branch: master
