language: csharp
mono: none
dotnet: 2.0.0
branches:
 only:
  - master
script:
  - dotnet build ./ContactList.WebApi/ContactList.sln -c Release
deploy:
  provider: pages
  skip-cleanup: true
  github-token: b5760e59cf512b17febee6f49452024b3ad7de0b
  keep-history: true
  on:
    branch: master
